apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-startup-deployment
  labels:
    app: streamlit-startup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-startup
  template:
    metadata:
      labels:
        app: streamlit-startup
    spec:
      containers:
      - name: streamlit-container
        image: europe-west2-docker.pkg.dev/plated-client-499118-m4/movie-analytics-repo/startup-app:latest
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "256Mi"   # Pehle 512Mi tha, optimized for small/free nodes
            cpu: "100m"       # Pehle 250m tha
          limits:
            memory: "512Mi"   # Pehle 1Gi tha
            cpu: "250m"       # Pehle 500m ram/cpu tha
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-startup-service
spec:
  type: LoadBalancer
  selector:
    app: streamlit-startup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501