apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-startup-deployment
  labels:
    app: streamlit-startup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-startup
  template:
    metadata:
      labels:
        app: streamlit-startup
    spec:
      containers:
      - name: streamlit-container
        image: europe-west2-docker.pkg.dev/plated-client-499118-m4/movie-analytics-repo/startup-app:latest
        imagePullPolicy: Always # Forces GKE to bypass cache and pull the fresh permission-fixed image
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-startup-service
spec:
  type: LoadBalancer
  selector:
    app: streamlit-startup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501